### ISSUE TITLE
todoMVC

### ISSUE THREAD

**Issue by vestild** [logux/examples#1]
I see it is zero examples yet.
Would it be usefull to add todoMVC example (maybe on vuex) as a starting point?

**Comment by ai** [comment]
Yeap, I didn’t finish the example yet

**Comment by vestild** [comment]
Have you started? I'll try to write it and if you have smth it would help me.

**Comment by ai** [comment]
Nope

**Comment by ai** [comment]
Moved to https://github.com/logux/logux/issues/5
