### ISSUE TITLE
docs: is this example to show syncing `between multi browser windows of same user` or `between different user`

### ISSUE THREAD

**Issue by uptonking** [logux/examples#19]
@ai
- syncing between multi browser of the same user works
- but I want to show sync between different user

**Comment by ai** [comment]
Just use channels, as it describe it docs

**Comment by burakakca** [comment]
This example works well on cross-browser. My code is pure js client example like you write.

```js
client.type('INC', (action, meta) => {
  counter.innerHTML = parseInt(counter.innerHTML) + 1
})

increase.addEventListener('click', () => {
  client.sync({ type: 'INC' })
})

loading.classList.add('is-show')
await client.sync({ type: 'logux/subscribe' channel: 'counter' })
loading.classList.remove('is-show')
```

What should I do for cross-browser, I wrote like this example but nothing happens

**Comment by burakakca** [comment]
I have code like you on the server and I use like you said the second rule
```js
server.channel('cube/:id', {
  access(ctx, action, meta) {
    return channels.includes(`cube/${ctx.params.id}`)
  },
  async load(ctx, action, meta) {
    //code...
  },
})
```

**Comment by burakakca** [comment]
Question: When an event is triggered like "INC". Do clients receive the event before or after the server?

**Comment by ai** [comment]
You need this code for `INC` action and `counter`:

```js
server.type('INC', {
  access () {
    return true // Allow all users to send this action
  },
  resend () {
    return 'counter' // Send this action to all users subscribed to couinter channel
  }
})

server.channel('counter', {
  access () {
    return true // Allow all users to subscribe to this channel
  },
  load () {
    // Load the initial state of counter on subscriptions. You can miss it for first test implementation.
  }
})
```

**Comment by ai** [comment]
> Question: When an event is triggered like "INC". Do clients receive the event before or after the server?

The current client (who created the action) received to before the server.

The other clients will receive it after the server.

**Comment by burakakca** [comment]
> You need this code for `INC` action and `counter`:
> 
> ```js
> server.type('INC', {
>   access () {
>     return true // Allow all users to send this action
>   },
>   resend () {
>     return 'counter' // Send this action to all users subscribed to couinter channel
>   }
> })
> 
> server.channel('counter', {
>   access () {
>     return true // Allow all users to subscribe to this channel
>   },
>   load () {
>     // Load the initial state of counter on subscriptions. You can miss it for first test implementation.
>   }
> })
> ```

I missed the resend method, thanks a lot
